### ISSUE TITLE
Don't use a callback

### ISSUE THREAD

**Issue by stevenvachon** [silverwind/port-numbers#6]
Callbacks are fine for asynchronous stuff, but not for getting data from a map. It slows it down and and messes up our code.

Instead, eager-load the json file when the library instantiates. You could even use `require("./db.json")` instead of `fs.readFile`.

**Comment by silverwind** [comment]
Yeah, I was in an async mindset lately, and totally ignored that this can be done cleany in a sync function. Thanks for pointing it out!
