### ISSUE TITLE
getPort performance

### ISSUE THREAD

**Issue by stevenvachon** [silverwind/port-numbers#7]
Running `Object.keys(db).some()` on that long map/object is a performance hit when calling `getPort()` multiple times. I think it'd be best to create a second map, indexed by protocol name (instead of port number) when the module is first loaded.

**Comment by stevenvachon** [comment]
Err, index by protocol name instead of port number. Edited original comment

**Comment by silverwind** [comment]
Good idea. I was wary of this costly iteration. Creating a second map will double the memory use, but it's probably the best solution.

**Comment by stevenvachon** [comment]
How much memory are we talking, though? Also, "memory is cheap".

**Comment by silverwind** [comment]
Not sure how well v8 stores JSON, but I assume at least the size it uses on the disk, so just 1 MB right now, maybe 2-3 MB in the future if I include all data fields. Not really an issue.

**Comment by stevenvachon** [comment]
:+1:
