### ISSUE TITLE
FTP description is a bit limited

### ISSUE THREAD

**Issue by stevenvachon** [silverwind/port-numbers#8]
https://github.com/silverwind/port-numbers/blob/master/ports.json#L184
https://github.com/silverwind/port-numbers/blob/master/ports.json#L188

No mention of "Protocol". This issue is far from major, but might cause a problem for some apps.

**Comment by silverwind** [comment]
There's nothing in [IANA's source](http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml) that further explains the acronym, and I'm not going to modify the source data, so I guess we have to live with it (or you bring up that issue to IANA, but its unlikely they will do changes to such a well-known protocol).
