### ISSUE TITLE
Please lazy-load ports.json

### ISSUE THREAD

**Issue by bengotow** [silverwind/port-numbers#9]
I stumbled across this repo today because `port-numbers` is a dependency of a dependency of a dependency of a library in https://github.com/nylas/N1. Loading 1MB of JSON (ports.json) takes a non-trivial amount of time and isn't used until `getPort` and `getService` are invoked, which in our case, is often never.

Please consider lazy-loading! 🙏

**Comment by silverwind** [comment]
Done, they are loaded on demand now.
